export const RECORDS_DB = {
  userName: "userName",
  location: "Location",
  startedAt: "Started At",
  weather: "Weather",
  temperature: "Temperature",
  maxTemp: "Max Temp",
  minTemp: "Min Temp",
  apparentTemp: "Apparent Temp",
  humidity: "Humidity",
  rainProb: "Rain Prob",
  uvIndex: "UV Index",
  photo: "Photo",
  upperBodyTags: "Upper Body Tags",
  lowerBodyTags: "Lower Body Tags",
  breathability: "Breathability",
  wrapping: "Wrapping",
  stuffiness: "Stuffiness",
} as const;
